services:

  traefik:
    image: traefik:v2.9
    # container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      # - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # - "/Users/arbianshkodra/.docker/run/docker.sock:/var/run/docker.sock:ro"
    # healthcheck:
    #   test: ["wget", "-q", "-O", "-", "http://localhost:80"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 3

  web1:
    # image: nginx:1.27.0
    image: nginx:1.26.1  # The image tag will be updated during deployment
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.<service>.entrypoints=web"
      - "traefik.http.routers.<service>.rule=PathPrefix(`/`)"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3