name: Release Dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '**/v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write
  packages: write

jobs:
  # lint:
  #   name: Lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Set up Go
  #       uses: actions/setup-go@v4
  #       with:
  #         go-version: 1.22.x

  #     - name: Static check
  #       uses: dominikh/staticcheck-action@v1.3.1
  #       with:
  #         version: "latest"
  #         install-go: "false"

  # test:
  #   name: Test
  #   strategy:
  #     matrix:
  #       go-version: [1.22.x]
  #       platform: [ubuntu-latest, macos-latest, windows-latest]
  #   runs-on: ${{ matrix.platform }}
  #   needs: [lint]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Set up Go
  #       uses: actions/setup-go@v4
  #       with:
  #         go-version: ${{ matrix.go-version }}

  #     - name: Run tests
  #       run: go test ./... -coverprofile coverage.out

  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    # needs: [lint, test]

  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.x

    - name: Build Binaries
      run: ./scripts/build_binaries.sh

    - name: Build Docker Image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: ./scripts/build_docker_image.sh

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.tar.gz
          dist/*.zip
          dist/checksums.txt
        generate_release_notes: true
