name: Release Docs Dev

on:
  workflow_run:
    workflows: ["Release Dev"]
    branch:
      # - main
      - dev
    types:
      - completed

permissions:
  contents: write

jobs:
  release-docs-dev:
    name: Release Docs Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Add requirements.txt
        run: |
          touch requirements.txt
          echo "mkdocs" >> requirements.txt
          echo "mkdocs-material" >> requirements.txt
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate documentation
        run: |
          mkdocs build
      - name: Install SSH Key
        run: |
          export PATH=$PATH:/bin:/usr/bin
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ${{ secrets.CERT_PATH }}
          chmod 600 ${{ secrets.CERT_PATH }}
          # Add server to known_hosts to prevent host key verification prompt
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      - name: Copy Files via SCP
        run: /usr/bin/scp -i ${{ secrets.CERT_PATH }} -r site/ ${{ secrets.USER }}@${{ secrets.HOST }}:${{ secrets.PATH }}

